name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  http: ^1.0.0
  flutter_spinkit: ^5.2.0
  
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: assets/fonts/SpartanMB-Black.otf
      weight: 900